export const kltnTopicsData = [
  {
    topicIndex: 1,
    title: "Xây dựng phần mềm quản lý quan hệ khách hàng bằng công nghệ ASP.Net và ReactJS trên nền tảng điện toán đám mây Microsoft Azure",
    supervisorName: "ThS. Đỗ Hà Phương",
    lecturerCode: "GV0012",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 2,
    title: "TRIỂN KHAI ỨNG DỤNG WEB ĐẶT LỊCH KHÁM BỆNH TRỰC TUYẾN",
    supervisorName: "ThS. Đỗ Hà Phương",
    lecturerCode: "GV0012",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 3,
    title: "Xây dựng website đặt hàng và quản lý sách tích hợp thanh toán trực tuyến",
    supervisorName: "ThS. Đỗ Hà Phương",
    lecturerCode: "GV0012",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 4,
    title: "Thuật toán tìm kiếm có đối thủ minimax và ứng dụng vào game tương tự",
    supervisorName: "ThS. Đỗ Hà Phương",
    lecturerCode: "GV0012",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 5,
    title: "Ứng dụng website đặt hàng và quản lý sách tích hợp thanh toán trực tuyến",
    supervisorName: "ThS. Đỗ Hà Phương",
    lecturerCode: "GV0012",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 6,
    title: "Xây dựng Website Tuyển dụng việc làm trên nền tảng đám mây AWS",
    supervisorName: "ThS. Đỗ Hà Phương",
    lecturerCode: "GV0012",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 7,
    title: "Xây dựng Website thương mại, tích hợp thanh toán cổng VNPay",
    supervisorName: "ThS. Đỗ Hà Phương",
    lecturerCode: "GV0012",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 8,
    title: "Xây dựng hệ thống website kinh doanh và quản lý nghiệp vụ nhà hàng tích hợp công nghệ Microservices",
    supervisorName: "ThS. Đỗ Hà Phương",
    lecturerCode: "GV0012",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 9,
    title: "NGHIÊN CỨU VÀ TRIỂN KHAI HỆ THỐNG PRIVATE CLOUD NUTANIX ỨNG DỤNG CẤP PHÁT TÀI NGUYÊN CHO MÁY CHỦ DOANH NGHIỆP",
    supervisorName: "ThS. Đỗ Hà Phương",
    lecturerCode: "GV0012",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 10,
    title: "Nghiên cứu và xây dựng Website bán máy tính và thiết bị PC",
    supervisorName: "ThS. Đỗ Hà Phương",
    lecturerCode: "GV0012",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 11,
    title: "Website thương mại điện tử dùng Laravel tích hợp VNPay, Momo, QR code cho thanh toán",
    supervisorName: "ThS. Đỗ Hà Phương",
    lecturerCode: "GV0012",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 12,
    title: "Xây dựng Chatbot SportLink - Hỗ trợ kết nối người chơi thể thao",
    supervisorName: "ThS. Đỗ Hà Phương",
    lecturerCode: "GV0012",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 13,
    title: "Xây dựng Website thương mại bán sản phẩm tiêu dùng hữu cơ",
    supervisorName: "ThS. Đỗ Hà Phương",
    lecturerCode: "GV0012",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 14,
    title: "Hệ thống phát hiện xâm nhập mã nguồn mở OSSEC và triển khai cho doanh nghiệp",
    supervisorName: "ThS. Hoàng Đình Hạnh",
    lecturerCode: "GV0003",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 15,
    title: "Hệ thống giám sát mạng mã nguồn mở ICINGA và triển khai cho doanh nghiệp",
    supervisorName: "ThS. Hoàng Đình Hạnh",
    lecturerCode: "GV0003",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 16,
    title: "Hệ thống giám sát mạng mã nguồn mở ZABBIX và triển khai cho doanh nghiệp",
    supervisorName: "ThS. Hoàng Đình Hạnh",
    lecturerCode: "GV0003",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 17,
    title: "Hệ thống lưu trữ mã nguồn mở CEPH triển khai cho doanh nghiệp",
    supervisorName: "ThS. Hoàng Đình Hạnh",
    lecturerCode: "GV0003",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 18,
    title: "Xây dựng hệ thống High Availability cho doanh nghiệp",
    supervisorName: "ThS. Hoàng Đình Hạnh",
    lecturerCode: "GV0003",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 19,
    title: "Giải pháp An toàn Máy chủ và Đảm bảo An toàn Dữ liệu cho Doanh nghiệp",
    supervisorName: "ThS. Hoàng Đình Hạnh",
    lecturerCode: "GV0003",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 20,
    title: "Tối ưu hóa Tài nguyên và Quản lý Máy ảo bằng Proxmox cho Doanh nghiệp",
    supervisorName: "ThS. Hoàng Đình Hạnh",
    lecturerCode: "GV0003",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 21,
    title: "Hỗ trợ người dùng thu thập dữ liệu và kích hoạt các thiết bị IOT, như Arduino, Raspberry Pi sử dụng các công cụ mây",
    supervisorName: "ThS. Nguyễn Thành Thái",
    lecturerCode: "GV0006",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 22,
    title: "Autonomous Car Robot",
    supervisorName: "ThS. Nguyễn Thành Thái",
    lecturerCode: "GV0006",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 23,
    title: "Hệ thống IoT giám sát và tự động hóa trang trại",
    supervisorName: "ThS. Nguyễn Thành Thái",
    lecturerCode: "GV0006",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 24,
    title: "Phát Triển Hệ Thống Website Đặt Vé Xem Phim Trực Tuyến Cho Chuỗi Rạp Chiếu Phim Bằng Công Nghệ Nodejs Và MySQL",
    supervisorName: "ThS. Nguyễn Văn Quang",
    lecturerCode: "GV0007",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 25,
    title: "Xây Dựng Web E-Commerce Bằng Công Nghệ Nodejs",
    supervisorName: "ThS. Nguyễn Văn Quang",
    lecturerCode: "GV0007",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 26,
    title: "CÔNG NGHỆ IOT QUẢN LÝ - GIÁM SÁT NHÀ NUÔI YẾN TỪ XA",
    supervisorName: "ThS. Nguyễn Văn Quang",
    lecturerCode: "GV0007",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 27,
    title: "Xây dựng Website E-commerce bằng PHP",
    supervisorName: "ThS. Nguyễn Văn Quang",
    lecturerCode: "GV0007",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 28,
    title: "Xây dựng hệ thống quản lý bán hàng",
    supervisorName: "ThS. Nguyễn Văn Quang",
    lecturerCode: "GV0007",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 29,
    title: "Ứng dụng ảo hóa cho doanh nghiệp nhỏ và ứng dụng",
    supervisorName: "ThS. Phạm Thái Khanh",
    lecturerCode: "GV0009",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 30,
    title: "Ứng dụng ảo hóa cho doanh nghiệp nhỏ và ứng dụng",
    supervisorName: "ThS. Phạm Thái Khanh",
    lecturerCode: "GV0009",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 31,
    title: "Ứng dụng ảo hóa cho doanh nghiệp nhỏ và ứng dụng",
    supervisorName: "ThS. Phạm Thái Khanh",
    lecturerCode: "GV0009",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 32,
    title: "NGHIÊN CỨU GIẢI PHÁP TỐI ƯU VÀ CẢI TIẾN MÔ HÌNH ĐỊNH TUYẾN MẠNG KHÔNG DÂY TRONG MÔI TRƯỜNG NƯỚC SỬ DỤNG METAHEURISTIC",
    supervisorName: "ThS. Võ Công Minh",
    lecturerCode: "GV0005",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 33,
    title: "Ứng dụng AI chuyển đổi nội dung Youtube thành bài viết",
    supervisorName: "ThS. Võ Công Minh",
    lecturerCode: "GV0005",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 34,
    title: "SỬ DỤNG NLP TRUY VẤN KẾT QUẢ AUDITING TRONG ORACLE DATABASE VÀ CẢNH BÁO QUA SIEM",
    supervisorName: "TS. Lê Thị Thúy",
    lecturerCode: "GV0004",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 35,
    title: "Truy vấn cơ sở dữ liệu Oracle bằng ngôn ngữ tự nhiên",
    supervisorName: "TS. Lê Thị Thúy",
    lecturerCode: "GV0004",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 36,
    title: "TRIỂN KHAI ROW LEVEL SECURITY, UNIFIED AUDITING TRONG ORACLE VÀ TÍCH HỢP SIEM TRÊN MỘT CSDL",
    supervisorName: "TS. Lê Thị Thúy",
    lecturerCode: "GV0004",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 37,
    title: "Tìm hiểu Security trong Oracle và hiện thực trên một Platform cụ thể",
    supervisorName: "TS. Lê Thị Thúy",
    lecturerCode: "GV0004",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 38,
    title: "Thu Thập và Phân Tích Dữ Liệu Quảng Cáo",
    supervisorName: "TS. Tạ Duy Công Chiến",
    lecturerCode: "GV0001",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 39,
    title: "Xây dựng web e-commerce sử dụng công nghệ Java",
    supervisorName: "TS. Tạ Duy Công Chiến",
    lecturerCode: "GV0001",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 40,
    title: "Tối ưu hóa trải nghiệm người dùng qua Hybrid Search trên nền tảng AWS trong website bán hàng thời trang",
    supervisorName: "TS. Trần Thị Minh Khoa",
    lecturerCode: "GV0002",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 41,
    title: "Xây dựng và triển khai website bản đồ nội thất",
    supervisorName: "TS. Trần Thị Minh Khoa",
    lecturerCode: "GV0002",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 42,
    title: "Mô phỏng trò chơi cờ vua với trí tuệ nhân tạo: Phân tích và triển khai Minimax cùng Alpha-beta Pruning",
    supervisorName: "TS. Trần Thị Minh Khoa",
    lecturerCode: "GV0002",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 43,
    title: "Xây dựng website thương mại điện tử tích hợp chấm công bằng nhận diện khuôn mặt cho doanh nghiệp kinh doanh nội thất",
    supervisorName: "TS. Trần Thị Minh Khoa",
    lecturerCode: "GV0002",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 44,
    title: "XÂY DỰNG WEBSITE ĐẶT VÉ TÀU VÀ ĐÁNH GIÁ HIỆU NĂNG TRIỂN KHAI TRÊN NỀN TẢNG AWS",
    supervisorName: "TS. Trần Thị Minh Khoa",
    lecturerCode: "GV0002",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 45,
    title: "Ứng dụng IOT trong quản lý nhà thông minh sử dụng Smart Mirror",
    supervisorName: "TS. Trần Thị Minh Khoa",
    lecturerCode: "GV0002",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
  {
    topicIndex: 46,
    title: "HỆ THỐNG IOT GIÁM SÁT PHÒNG SERVER VỚI GRAFANA & INFLUXDB",
    supervisorName: "TS. Trần Thị Minh Khoa",
    lecturerCode: "GV0002",
    semester: "HK1",
    academicYear: "2026-2027",
    termCode: "HK1_2026_2027",
  },
];
